{
	"title": "Add fallbacks | ü¶úÔ∏èüîó Langchain",
	"url": "https://python.langchain.com/docs/expression_language/how_to/fallbacks",
	"html": "LangChain Expression LanguageHow toAdd fallbacks\nAdd fallbacks\n\nThere are many possible points of failure in an LLM application, whether that be issues with LLM API's, poor model outputs, issues with other integrations, etc. Fallbacks help you gracefully handle and isolate these issues.\n\nCrucially, fallbacks can be applied not only on the LLM level but on the whole runnable level.\n\nHandling LLM API Errors‚Äã\n\nThis is maybe the most common use case for fallbacks. A request to an LLM API can fail for a variety of reasons - the API could be down, you could have hit rate limits, any number of things. Therefore, using fallbacks can help protect against these types of things.\n\nIMPORTANT: By default, a lot of the LLM wrappers catch errors and retry. You will most likely want to turn those off when working with fallbacks. Otherwise the first wrapper will keep on retrying and not failing.\n\nfrom langchain.chat_models import ChatAnthropic, ChatOpenAI\n\n\nFirst, let's mock out what happens if we hit a RateLimitError from OpenAI\n\nfrom unittest.mock import patch\n\nfrom openai.error import RateLimitError\n\n# Note that we set max_retries = 0 to avoid retrying on RateLimits, etc\nopenai_llm = ChatOpenAI(max_retries=0)\nanthropic_llm = ChatAnthropic()\nllm = openai_llm.with_fallbacks([anthropic_llm])\n\n# Let's use just the OpenAI LLm first, to show that we run into an error\nwith patch(\"openai.ChatCompletion.create\", side_effect=RateLimitError()):\n    try:\n        print(openai_llm.invoke(\"Why did the chicken cross the road?\"))\n    except:\n        print(\"Hit error\")\n\n    Hit error\n\n# Now let's try with fallbacks to Anthropic\nwith patch(\"openai.ChatCompletion.create\", side_effect=RateLimitError()):\n    try:\n        print(llm.invoke(\"Why did the chicken cross the road?\"))\n    except:\n        print(\"Hit error\")\n\n    content=' I don\\'t actually know why the chicken crossed the road, but here are some possible humorous answers:\\n\\n- To get to the other side!\\n\\n- It was too chicken to just stand there. \\n\\n- It wanted a change of scenery.\\n\\n- It wanted to show the possum it could be done.\\n\\n- It was on its way to a poultry farmers\\' convention.\\n\\nThe joke plays on the double meaning of \"the other side\" - literally crossing the road to the other side, or the \"other side\" meaning the afterlife. So it\\'s an anti-joke, with a silly or unexpected pun as the answer.' additional_kwargs={} example=False\n\n\nWe can use our \"LLM with Fallbacks\" as we would a normal LLM.\n\nfrom langchain.prompts import ChatPromptTemplate\n\nprompt = ChatPromptTemplate.from_messages(\n    [\n        (\n            \"system\",\n            \"You're a nice assistant who always includes a compliment in your response\",\n        ),\n        (\"human\", \"Why did the {animal} cross the road\"),\n    ]\n)\nchain = prompt | llm\nwith patch(\"openai.ChatCompletion.create\", side_effect=RateLimitError()):\n    try:\n        print(chain.invoke({\"animal\": \"kangaroo\"}))\n    except:\n        print(\"Hit error\")\n\n    content=\" I don't actually know why the kangaroo crossed the road, but I'm happy to take a guess! Maybe the kangaroo was trying to get to the other side to find some tasty grass to eat. Or maybe it was trying to get away from a predator or other danger. Kangaroos do need to cross roads and other open areas sometimes as part of their normal activities. Whatever the reason, I'm sure the kangaroo looked both ways before hopping across!\" additional_kwargs={} example=False\n\nSpecifying errors to handle‚Äã\n\nWe can also specify the errors to handle if we want to be more specific about when the fallback is invoked:\n\nllm = openai_llm.with_fallbacks(\n    [anthropic_llm], exceptions_to_handle=(KeyboardInterrupt,)\n)\n\nchain = prompt | llm\nwith patch(\"openai.ChatCompletion.create\", side_effect=RateLimitError()):\n    try:\n        print(chain.invoke({\"animal\": \"kangaroo\"}))\n    except:\n        print(\"Hit error\")\n\n    Hit error\n\nFallbacks for Sequences‚Äã\n\nWe can also create fallbacks for sequences, that are sequences themselves. Here we do that with two different models: ChatOpenAI and then normal OpenAI (which does not use a chat model). Because OpenAI is NOT a chat model, you likely want a different prompt.\n\n# First let's create a chain with a ChatModel\n# We add in a string output parser here so the outputs between the two are the same type\nfrom langchain.schema.output_parser import StrOutputParser\n\nchat_prompt = ChatPromptTemplate.from_messages(\n    [\n        (\n            \"system\",\n            \"You're a nice assistant who always includes a compliment in your response\",\n        ),\n        (\"human\", \"Why did the {animal} cross the road\"),\n    ]\n)\n# Here we're going to use a bad model name to easily create a chain that will error\nchat_model = ChatOpenAI(model_name=\"gpt-fake\")\nbad_chain = chat_prompt | chat_model | StrOutputParser()\n\n# Now lets create a chain with the normal OpenAI model\nfrom langchain.llms import OpenAI\nfrom langchain.prompts import PromptTemplate\n\nprompt_template = \"\"\"Instructions: You should always include a compliment in your response.\n\nQuestion: Why did the {animal} cross the road?\"\"\"\nprompt = PromptTemplate.from_template(prompt_template)\nllm = OpenAI()\ngood_chain = prompt | llm\n\n# We can now create a final chain which combines the two\nchain = bad_chain.with_fallbacks([good_chain])\nchain.invoke({\"animal\": \"turtle\"})\n\n    '\\n\\nAnswer: The turtle crossed the road to get to the other side, and I have to say he had some impressive determination.'\n\nPrevious\nConfigure chain internals at runtime\nNext\nRun custom functions"
}